server:
  port: 8084
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 0
    pool:
      max-active: 10
      max-wait: -1
  application:
    name: hey
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: 123456
#    virtual-host: /
  boot:
    admin:
      context-path: sba

